name: CI 

on: 
  [ push, workflow_dispatch ]

permissions:
  contents: read
  packages: read
      
jobs:
  build:
    
    runs-on: ubuntu-20.04
    
    strategy:
      matrix:
        version: [ 12.6.0 ]
    
    steps:

      - name: Checkout repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8         # v3.1.0
        with:
          path: src

      - name: Get version info
        run: |
          v=${{matrix.version}}
          flatversion=`echo ${v%\.*} | sed "s/\.//g"`
          echo flattened minor version: $flatversion
          echo "FLATVERSION=${flatversion}" >> $GITHUB_ENV
          echo "OPENEDGE_VERSION=${{matrix.version}}" >> $GITHUB_ENV

      - name: Insert JDK version in Dockerfile
        run: |
          jdk=`jq -r ".jdk${FLATVERSION}" src/jdk-versions.json`
          echo JDK: $jdk
          sed -i "s/JDKVERSION/$jdk/g" src/Dockerfile
          echo download jdk from Dockerfile:
          cat src/Dockerfile | grep temurin
  
      - name: Download installer files
        run: |
          docker run -v ${PWD}/src:/target devbfvio/oeinstaller:${{env.OPENEDGE_VERSION}}
      
      - name: Get response.ini  # get progress.cfg from secret PROGRESS_CFG_122
        run: |
          echo fetching response.ini/progress.cfg from secret RESPONSE_INI_${{env.FLATVERSION}}
          echo "${{ secrets[format('RESPONSE_INI_{0}', env.FLATVERSION)] }}" > src/response.ini
          echo "${{ secrets[format('PROGRESS_CFG_{0}', env.FLATVERSION)] }}" | base64 --decode > src/progress.cfg
          ls -l src
