name: Copy Docker tag

on:
  workflow_dispatch:
    inputs:
      source_tag:
        type: string
        description: "source tag"
        default: "12.8.8"
        required: true
      target_tag:
        type: string
        description: "target tag"
        default: "latest"
        required: true

run-name: copy tag ${{ github.event.inputs.source_tag }} to ${{ github.event.inputs.target_tag }}

jobs:
    copy:
        runs-on: ubuntu-latest
        steps:

            - name: Setup image ref
              run: |
                echo "Setting up image ref"
                echo "IMAGE_NAME=${{ vars.REGISTRY_DOMAIN }}/${{ vars.IMAGE_PREFIX}}openedge-pas" >> $GITHUB_ENV
                echo 

            - name: Display info
              run: |
                echo "Displaying info"
                echo "IMAGE_NAME=${{ vars.REGISTRY_DOMAIN }}/${{ vars.IMAGE_PREFIX}}openedge-pas"
                echo "source_tag=${{ github.event.inputs.source_tag }}"
                echo "target_tag=${{ github.event.inputs.target_tag }}"

            - name: Login to registry
              uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20  # v3.1.0
              with:
                registry: ${{ vars.REGISTRY_DOMAIN }}
                username: ${{ secrets.REGISTRY_USERNAME }}
                password: ${{ secrets.REGISTRY_PASSWORD }}
            
            - name: Copy docker tag
              run: |
                echo "Copying tag ${{ github.event.inputs.source_tag }} to ${{ github.event.inputs.target_tag }}"
                docker pull ${{ env.IMAGE_NAME}}:${{ github.event.inputs.source_tag }}
                docker tag ${{ env.IMAGE_NAME}}:${{ github.event.inputs.source_tag }} ${{ env.IMAGE_NAME}}:${{ github.event.inputs.target_tag }}
                docker push ${{ env.IMAGE_NAME}}:${{ github.event.inputs.target_tag }}


